### ISSUE TITLE
Using a different opt-level (than the default) fails to link the correct libraries.

### ISSUE THREAD

**Issue by andriyDev** [andriyDev/recastnavigation-rs-sys#4]
Putting:
```toml
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
```
in Cargo.toml (I put it in my workspaces toml if that matters) tries to link `Recast-d`, but cmake builds `Recast`, so it fails to link.

Context: Bevy says to use these options!
